### ISSUE TITLE
connect to ftp success,but login failed(user/password has been checked)

### ISSUE THREAD

**Issue by yangshaohongit** [nopnop2002/esp-idf-ftpClient#14] opened 2024-10-26 04:20 UTC
Here are the log

(6095) FTP: Mounte SD card on /root
I (6095) FTP: ftp server:192.168.253.39
I (6105) FTP: ftp user  :ftpuser
I (11565) FTP: connect=1
I (11565) FTP: set connect mode=1
I (11635) FTP: login=0
E (11635) FTP: FTP server login fail
I (11635) main_task: Returned from app_main()

**Comment by nopnop2002** [comment] 2024-10-26 09:27
I think this log is the cause.
```
I (11565) FTP: set connect mode=1
```

It's not in my log.

```
I (4974) FTP: Mount SPIFFS filesystem on /root
I (4974) FTP: ftp server:192.168.10.11
I (4984) FTP: ftp user  :pi
I (5484) FTP: connect=1
I (5634) FTP: login=1
```

**Comment by nopnop2002** [comment] 2024-11-05 22:44
I will close this issue.
You can Reopen at any time.

**Closed as completed by nopnop2002** 2024-11-05 22:44 UTC
